export enum ErrorCode {
  CART_EMPTY = 'CART_EMPTY',
  ITEMS_UNAVAILABLE = 'ITEMS_UNAVAILABLE',
  STOCK_EXCEEDED = 'STOCK_EXCEEDED',
  SHIPPING_UNAVAILABLE = 'SHIPPING_UNAVAILABLE',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  INVALID_INPUT = 'INVALID_INPUT',
  STRIPE_ERROR = 'STRIPE_ERROR',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  ORDER_META_NOT_FOUND = 'ORDER_META_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
