import * as fs from 'node:fs'
import * as path from 'node:path'
import Image from '@11ty/eleventy-img'
import type { CoreContext } from "../types";
import { sanityPicture, staticPicture, type PictureSize, type PictureOptions } from "../image";

export const createShortcodes = (ctx: CoreContext) => {
  const { eleventyConfig, imageBuilder, config, imageSizes } = ctx

  eleventyConfig.addShortcode("sanityPicture", (image, size, options) =>
    sanityPicture(imageBuilder, image, size, options)
  )

  // Pre-generate static images before build so statsSync URLs resolve to real files.
  // Collects all widths/formats from the merged imageSizes config and processes
  // every file in src/assets/images/static/ with those settings.
  if (!config.preview?.enabled) {
    const allWidths = [...new Set(Object.values(imageSizes).flatMap((s: PictureSize) => s.sizes.map(([w]) => w)))]
    const allFormats = [...new Set(Object.values(imageSizes).flatMap((s: PictureSize) =>
      (s.formats ?? ['webp']).map(f => f === 'jpg' ? 'jpeg' : f)
    ))]

    eleventyConfig.on('eleventy.before', async () => {
      const inputDir = eleventyConfig.directories?.input ?? 'src'
      const staticDir = path.join(process.cwd(), inputDir, 'assets/images/static')
      if (!fs.existsSync(staticDir)) return
      const files = fs.readdirSync(staticDir).filter(f => /\.(png|jpe?g|gif|webp)$/i.test(f))
      for (const file of files) {
        await Image(path.join(staticDir, file), {
          widths: allWidths,
          formats: allFormats,
          outputDir: path.join(process.cwd(), 'dist/assets/images/'),
          urlPath: '/assets/images/',
        })
      }
    })
  }

  // Sync shortcode — works in all Nunjucks contexts including dynamic includes.
  // Images are pre-generated by the eleventy.before hook above.
  eleventyConfig.addShortcode("staticPicture", (src: string, size: PictureSize, options: PictureOptions) =>
    staticPicture(src, size, options)
  )
}
